Add type enforcement to cvmfs::mount and cvmfs::domain
voxpupuli/puppet-cvmfs pull request #122
Opened 2021-03-16 10:32 UTC by traylenator

#### Pull Request (PR) description

Add type enforcement to `cvmfs::mount` and `cvmfs::domain`

In addition enforce all parameters are documented with puppet strings
using a linter.

Add puppet strings everywhere.

2021-03-16 10:33 UTC, traylenator commented
Worth adding I plan to do a complete proof read of all docs before a next release.

2021-03-17 21:32 UTC, luisfdez requested changes

2021-03-17 21:32 UTC, luisfdez commented on manifests/domain.pp
> +  Optional[Integer] $cvmfs_quota_limit             = undef,
It seems that `cvmfs_quota_limit` is not used as is in `repo.local.erb`, it refers to `my_cvmfs_quota_limit` as passed from `config.pp`.

2021-03-17 21:32 UTC, luisfdez commented on manifests/domain.pp
> +  Optional[Stdlib::Yes_no] $cvmfs_force_singing    = undef,
Is this one used?

2021-03-17 21:32 UTC, luisfdez commented on manifests/mount.pp
> +  Optional[Integer]  $cvmfs_quota_limit                             = undef,
Same as before. It seems that we should apply the same transform to `cvmfs_quota_limit` as `config.pp` as the `erb` refers to `@my_cvmfs_quota_limit`.

2021-03-17 21:32 UTC, luisfdez commented on manifests/mount.pp
> +  Boolean$cvmfs_repo_list                                           = true,
```suggestion
  Boolean $cvmfs_repo_list                                           = true,
```

2021-03-18 07:44 UTC, traylenator commented on manifests/domain.pp
> +  Optional[Stdlib::Yes_no] $cvmfs_force_singing    = undef,
cvmfs_force_singing  is completly gone.

2021-03-18 07:48 UTC, bastelfreak commented on .sync.yml
> +      - gem: puppet-lint-param-docs
\o/

2021-03-18 07:50 UTC, bastelfreak approved these changes

2021-03-18 08:16 UTC, merged