Add param to simplify loading `cvmfs::fsck`
voxpupuli/puppet-cvmfs pull request #152
Opened 2022-04-15 16:00 UTC by jcpunk

#### Pull Request (PR) description
Add a simple parameter to ease loading `cvmfs::fsck` via arguments.

#### This Pull Request (PR) fixes the following issues
None

2022-04-19 12:47 UTC, traylenator requested changes
Prefer `cmvfs_fsck` over

2022-04-19 12:47 UTC, traylenator commented on manifests/init.pp
> +# @param cvmfs_include_fsck Ensure the cvmfs::fsck class is included.
```suggestion
# @param cvmfs_fsck Ensure the cvmfs::fsck class is included.
```
Don't think we want include in variable name as the method does not need to be exposed.

2022-04-19 12:47 UTC, traylenator commented on manifests/init.pp
> +  Boolean $cvmfs_include_fsck                                         = false,
```suggestion
  Boolean $cvmfs_fsck                                         = false,
```

2022-04-19 12:47 UTC, traylenator commented on manifests/init.pp
> +  if $cvmfs_include_fsck {
```suggestion
  if $cvmfs_fsck {
```

2022-04-19 12:47 UTC, traylenator commented on spec/classes/init_spec.rb
> +          context 'with cvmfs_include_fsck set to true' do
```suggestion
          context 'with cvmfs_fsck set to true' do
```

2022-04-19 12:47 UTC, traylenator commented on spec/classes/init_spec.rb
> +              { cvmfs_include_fsck: true,
```suggestion
              { cvmfs_fsck: true,
```

2022-04-19 12:51 UTC, traylenator commented
If we add that option we may as well go the whole way and make cvmfs::fsck a private interface that gets it values from the cvmfs class.

So:

```puppet
class cvmfs::fsck (                            
  $cvmfs_cache_base = $cvmfs::cvmfs_cache_base,
  $options =  $cvmfs::cvmfs_fsck_options,
  $onreboot = $cvmfs::cvmfs_fsck_onreboot,
  Optional[Boolean] $usesystemd = undef,
) inherits cvmfs {

```
As for last usesystemd this looks be completly unnecessary these days. Leave as undef.

2022-04-19 19:18 UTC, jcpunk commented
I've attempted to resolve all requested changes.

2022-04-20 14:15 UTC, traylenator requested changes
Code all looks fine.

Can you update the README as it still references the cvmfs::fsck which is now not needed.
Can the @params at the top of `cvmfs::fsck` be replaced with:

# @api private

Lets make this backwards incompatible even if the old API still works.
Better that folk know that old api is gone even if it still works.

2022-04-20 14:32 UTC, jcpunk commented
Sounds good.  I'll confess, I have no idea how to export the values in rspec to get the tests happy.....

2022-04-20 14:49 UTC, jcpunk commented
Works for me, I've put the params (and their doc to make the analysis happy) back and dropped `assert_private`

2022-05-05 19:56 UTC, jcpunk commented
This version look viable?

2022-06-27 07:50 UTC, merged