Add ownership of cachedir to puppet if claiming ownership
voxpupuli/puppet-cvmfs pull request #190
Opened 2024-01-31 14:57 UTC by jcpunk

#### Pull Request (PR) description
Add ownership of cvmfs cachedir to puppet when `cvmfs::cvmfs_claim_ownership` - `"yes"`

#### This Pull Request (PR) fixes the following issues

2024-02-01 09:42 UTC, traylenator commented
I had not realised we were missing type definitions everywhere - may be easier if I fix that first.

2024-02-05 16:11 UTC, jcpunk commented
Rebased off `HEAD`

2024-02-05 16:13 UTC, traylenator requested changes

2024-02-05 16:13 UTC, traylenator commented on manifests/install.pp
> +  if (downcase($cvmfs_claim_ownership) == 'yes') or ($cvmfs_cache_base != $default_cvmfs_cache_base) {
```suggestion
  if ($cvmfs_claim_ownership == 'yes') or ($cvmfs_cache_base != $default_cvmfs_cache_base) {
```
can drop the downcase now.

2024-02-06 09:53 UTC, traylenator approved these changes

2024-02-06 09:54 UTC, traylenator commented
Will get  release out shortly.

2024-02-06 09:54 UTC, merged

2024-02-07 16:49 UTC, jcpunk commented
I suspect you got distracted...